---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nander.
--- DateTime: 2/28/19 4:08 PM
---

return function(text)
    return {
        func = function(data) print(data) end,
        data = text,
        object = nil,
    }
end