---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nander.
--- DateTime: 2/28/19 2:49 PM
---

local system = {}

system.pauses = true

system.update = function(dt)

end
system.reset = function () end
system.name = "circles_on_position"
return system